name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches: ["feature/**", "main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  DOTNET_VERSION: '10.x'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - project: BlazorWebAppWithKeycloak
            name: APP
            repository: ${{ vars.BLAZOR_REPOSITORY }}
          - project: BlazorWebAppWithKeycloak.API
            name: API
            repository: ${{ vars.API_REPOSITORY }}

    name: Build ${{ matrix.name }}

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: GitVersion
        uses: dotnet/nbgv@master
        id: nbgv
        with:
          path: ${{ matrix.project }}

      - name: Build and publish container image
        run: |
          dotnet publish ${{ matrix.project }}/${{ matrix.project }}.csproj \
            -c Release /t:PublishContainer \
            -p:ContainerRegistry=${{ secrets.CONTAINER_REGISTRY }} \
            -p:ContainerRepository=${{ matrix.repository }} \
            -p:ContainerImageTags='"latest;${{ steps.nbgv.outputs.SemVer2 }}"'
        env:
          SDK_CONTAINER_REGISTRY_UNAME: ${{ secrets.DOCKER_USER }}
          SDK_CONTAINER_REGISTRY_PWORD: ${{ secrets.DOCKER_PASSWORD }}
