name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches: ["feature/**", "main"]
  pull_request:
    branches: ["main"]

env:
    DOTNET_VERSION: '10.x' # The .NET SDK version to use
    BUILD_WORKING_DIRECTORY: 'BlazorWebAppWithKeycloak'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: GitVersion
        uses: dotnet/nbgv@master
        id: nbgv        
        with:
           path: ${{ env.BUILD_WORKING_DIRECTORY }}

      - name: Build and publish container image
        run: |
          dotnet publish \
            -c Release \
            /t:PublishContainer \
            -p:ContainerRegistry=${{ secrets.DOCKER_REGISTRY }} \
            -p:ContainerRepository=${{ secrets.DOCKER_REPOSITORY }} \
            -p:ContainerImageTags="${{ steps.nbgv.outputs.SemVer2 }},latest" \
            -p:ContainerPush=true \
            -p:ContainerRegistryUsername=${{ secrets.DOCKER_USER }} \
            -p:ContainerRegistryPassword=${{ secrets.DOCKER_PASSWORD }}
        working-directory: ${{ env.BUILD_WORKING_DIRECTORY }}